
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";



--
-- Base de Dados: `CardGame`
--
CREATE DATABASE IF NOT EXISTS `CardGame` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `CardGame`;

-- --------------------------------------------------------

--
-- Estrutura da tabela `TB_USUARIO`
--

CREATE TABLE IF NOT EXISTS `TB_USUARIO` (
  `CD_USUARIO` int NOT NULL AUTO_INCREMENT,
  `NM_USUARIO` varchar(100) NOT NULL,
  `NR_SENHA` int(8) NOT NULL,
  `TP_USUARIO` ENUM('USER','ADMIN') NOT NULL,
  PRIMARY KEY (`CD_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- ------------------------------------------------------

-- Estrutura da tabela `TB_UNIVERSO`

CREATE TABLE IF NOT EXISTS `TB_UNIVERSO` (
  `CD_UNIVERSO` int NOT NULL AUTO_INCREMENT,
  `CAMINHO_IMG_UNIVERSO` varchar(255) NOT NULL,
  `NM_UNIVERSO` varchar(100) NOT NULL,
  PRIMARY KEY (`CD_UNIVERSO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- ------------------------------------------------------

-- Estrutura da tabela `TB_HABILIDADE`

CREATE TABLE IF NOT EXISTS `TB_HABILIDADE` (
  `CD_HABILIDADE` int NOT NULL AUTO_INCREMENT,
  `NM_HABILIDADE` varchar(50) NOT NULL,
  `DS_HABILIDADE` varchar(255) NOT NULL,
  `LV_HABILIDADE` ENUM('1','2','3','4','5') NOT NULL,
  PRIMARY KEY (`CD_HABILIDADE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


-- ------------------------------------------------------

-- Estrutura da tabela `TB_CARTA`
CREATE TABLE IF NOT EXISTS `TB_CARTA` (
  `CD_CARTA` int NOT NULL AUTO_INCREMENT,
  `NM_CARTA` varchar(20) NOT NULL,
  `CAMINHO_IMG_CARTA` VARCHAR(255) NOT NULL,
  `DS_CARTA` VARCHAR(255) NOT NULL,
  `TP_CARTA` ENUM('Comum','Uncomum','Rara','Épica','Lendária','Mítica') NOT NULL,
  `ATB_FORCA` INT(8) NOT NULL,
  `ATB_VELOCIDADE` INT(8) NOT NULL,
  `ATB_INTELIGENCIA` INT(8) NOT NULL,
  `ATB_VITALIDADE` INT(8) NOT NULL,
  `ATB_RESISTENCIA` INT(8) NOT NULL,
  `CD_UNIVERSO` int NOT NULL,
  PRIMARY KEY (`CD_CARTA`),
  FOREIGN KEY (`CD_UNIVERSO`) REFERENCES `TB_UNIVERSO`(`CD_UNIVERSO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- ----------------------------------------------------------

-- Estrutura da tabela `TB_HABILIDADE_CARTA`
CREATE TABLE IF NOT EXISTS `TB_HABILIDADE_CARTA` (
  `CD_HABILIDADE_CARTA` int NOT NULL AUTO_INCREMENT,
  `CD_HABILIDADE` int NOT NULL,
  `CD_CARTA` int NOT NULL,
  PRIMARY KEY (`CD_HABILIDADE_CARTA`),
  FOREIGN KEY (`CD_HABILIDADE`) REFERENCES `TB_HABILIDADE`(`CD_HABILIDADE`),
  FOREIGN KEY (`CD_CARTA`) REFERENCES `TB_CARTA`(`CD_CARTA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- ---------------------------------------------------------

-- Estrutura da tabela `TB_CARTAS_USUARIO`
CREATE TABLE IF NOT EXISTS `TB_CARTAS_USUARIO` (
  `CD_CARTAS_USUARIO` int NOT NULL AUTO_INCREMENT,
  `CD_USUARIO` int NOT NULL,
  `CD_CARTA` int NOT NULL,
  PRIMARY KEY (`CD_CARTAS_USUARIO`),
  FOREIGN KEY (`CD_USUARIO`) REFERENCES `TB_USUARIO`(`CD_USUARIO`),
  FOREIGN KEY (`CD_CARTA`) REFERENCES `TB_CARTA`(`CD_CARTA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;



-- ---------------------------------------

-- Criação de um usuario administrador padrão

INSERT INTO `tb_usuario` (`NM_USUARIO`, `NR_SENHA`, `TP_USUARIO`) VALUES
('Isaac', 12345678, 'ADMIN');